### ISSUE TITLE
Improve documentation for REQUIRED_SETTINGS

### ISSUE THREAD

**Issue by rafaellott** [drgarcia1986/simple-settings#53]
Is possible to improve the documentation regarding the 'REQUIRED_SETTINGS'?

I didn't get how do you define that configuration.

Is the SIMPLE_SETTINGS = {...} a global variable? Or do you need to call a function before getting the 'from simple_settings import settings'?

**Comment by drgarcia1986** [comment]
Hi @rafaellott 
The special settings are defined in variable `SIMPLE_SETTINGS` inside your settings file, e.g.:

```python
FOO = 'some string'

SIMPLE_SETTINGS = {
    'REQUIRED_SETTINGS': ('FOO', 'BAR')
}
```

After the first settings are readed this validation run (because the `settings` object is lazy) . A good idea is to create a method called `check` to run validation before used.

Do you read the [special settings documentation](http://simple-settings.readthedocs.io/en/latest/#special-settings) ?

**Comment by rafaellott** [comment]
Hi @drgarcia1986 

Now I got it! I thought you needed to add the SIMPLE_SETTINGS into the app.py file, not in the settings file.

It worked perfectly, thank for your help and for the lib! Saved me lot of time.

**Comment by drgarcia1986** [comment]
You're welcome @rafaellott
